[project]
name = "AI_learning"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "accelerate>=1.11.0",
    "adapters>=1.2.0",
    "bitsandbytes>=0.48.2",
    "huggingface-hub>=0.36.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "transformers>=4.51.3",
]
