[project]
name = "AI_learning"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "accelerate>=1.11.0",
    "bitsandbytes>=0.48.2",
    "dotenv>=0.9.9",
    "hf-xet>=1.2.0",
    "huggingface-hub>=0.36.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "sentence-transformers>=5.1.2",
    "transformers>=4.51.3",
]
